# Generated by Django 4.1.7 on 2023-05-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentification", "0002_filesupload"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricasHeatmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1", models.FloatField()),
                ("roc_auc", models.FloatField()),
                ("time", models.FloatField()),
            ],
        ),
    ]
